---
- name: Setup gitlab certificates
  command: openssl req -new -nodes -x509 -subj "/C=FR/ST=Paris/L=Paris/O=IT/CN={{ gitlab_hostname }}" -days {{certificate_validity_period_in_days}} -keyout /etc/nginx/ssl/gitlab_server.key -out /etc/nginx/ssl/gitlab_server.crt -extensions v3_ca creates=/etc/nginx/ssl/gitlab_server.crt
  notify: Reload nginx

- name: Create gitlab virtual host
  template: src=virtual_host_config dest=/etc/nginx/sites-available/gitlab
  notify: Reload nginx

- name: Create gitlab link in site-enabled
  file: src=/etc/nginx/sites-available/gitlab state=link dest=/etc/nginx/sites-enabled/gitlab
  notify: Reload nginx 

- name: Create line for gitlab in /etc/hosts
  lineinfile: dest=/etc/hosts line="127.0.0.1 {{ gitlab_hostname }}" insertafter="^127"
