---
- name: Add backports repository
  apt_repository: repo="deb {{backport_uri}} {{debian_version_name}}-backports main contrib non-free" state=present update_cache=yes

- name: Upgrade to latest packages
  apt: upgrade=full

- name: Install base packages
  apt: name={{ item }} state=present
  with_items:
    - curl
    - htop
    - rsync
    - tar
    - git
    - sudo
    - python-setuptools

- name: Remove unused packages
  apt: name={{ item }} state=absent purge=yes
  with_items:
    - exim4
    - exim4-daemon-light
    - exim4-daemon-heavy
    - apache2-bin
    - apache2-data

- name: Install pip
  easy_install: name=pip
