---
- name: Add backports repository
  apt_repository: repo="deb {{backport_uri}} {{debian_version_name}}-backports main contrib non-free" state=present update_cache=yes

- name: Upgrade to latest packages
  apt: upgrade=full

- name: Install base packages
  apt: 
    name: 
      - curl
      - htop
      - rsync
      - tar
      - git
      - sudo
      - python-setuptools
    state: present

- name: Remove unused packages
  apt:
    name:
      - exim4
      - exim4-daemon-light
      - exim4-daemon-heavy
      - apache2-bin
      - apache2-data
    state: absent
    purge: yes