---
- name: Add remote user as sudoer
  lineinfile: dest=/etc/sudoers state=present line="{{ansible_ssh_user}} ALL=(ALL:ALL) ALL"
  register: remote_user_as_sudo_user

- name: Reload sudo configuration after adding remote user
  service: name=sudo state=restarted
  when: remote_user_as_sudo_user|changed

- name: Create owncloud database user
  become: yes
  become_method: sudo
  become_user: postgres
  postgresql_user: name={{owncloud_database_user}} password={{owncloud_database_user_password}} role_attr_flags=NOSUPERUSER,CREATEDB state=present

- name: Create owncloud database
  become: yes
  become_method: sudo
  become_user: postgres
  postgresql_db: name={{owncloud_database_name}} owner={{owncloud_database_user}} state=present 

- name: Remove remote user as sudoer
  lineinfile: dest=/etc/sudoers state=absent line="{{ansible_ssh_user}} ALL=(ALL:ALL) ALL"
  register: remote_user_not_sudo_user

- name: Reload sudo configuration after removing remote user
  service: name=sudo state=restarted
  when: remote_user_not_sudo_user|changed
