---
- name: "Install vincent useful packages : zsh, vim, irssi, screen."
  apt: pkg={{ item }} state=present 
  become: yes
  become_method: su
  with_items:
    - zsh
    - screen
    - vim
    - irssi

- name: Create vincent user
  user: name=vincent shell=/bin/zsh
  become: yes
  become_method: su

- name: Copy vimrc file configuration to vincent home
  copy: dest=/home/vincent/.vimrc src=vimrc owner=vincent group=vincent mode=0644

- name: Copy vim specific configuration files to vincent home
  copy: dest=/home/vincent/.vim src=vim/ owner=vincent group=vincent mode=0644

- name: Copy zshrc file configuration to vincent home
  copy: dest=/home/vincent/.zshrc src=zshrc owner=vincent group=vincent mode=0644

- name: Copy zsh specific configuration files to vincent home
  copy: dest=/home/vincent/.zsh src=zsh/ owner=vincent group=vincent mode=0644

- name: Copy irssi configuration files to vincent home
  copy: dest=/home/vincent/.irssi src=irssi/ owner=vincent group=vincent mode=0644

- name: Copy screenrc file configuration to vincent home
  copy: dest=/home/vincent/.screenrc src=screenrc owner=vincent group=vincent mode=0644

- name: Set authorized keys for vincent
  authorized_key: user=vincent
                   key="{{ item }}"
  with_file:
  - public_keys/blue
  - public_keys/heilong
