---
- name: Install certbot
  apt:
    name: certbot
    state: latest

- name: Generate Certificate for Domains
  shell: certbot --nginx -d 'doba.fr,vincent.doba.fr' -m {{ email }} --agree-tos -n --nginx-ctl '/usr/sbin/nginx' --redirect

- name: "Disable TLS 1.0 and 1.1"
  lineinfile:
    path: /etc/letsencrypt/options-ssl-nginx.conf
    regexp: '^ssl_protocols TLSv1 TLSv1\.1 TLSv1\.2;'
    line: "ssl_protocols TLSv1.2 TLSv1.3;"
  notify: Restart nginx

- name: Add automatic certificate renewal
  cron:
    name: Certbot automatic renewal
    job: "certbot renew --quiet --no-self-upgrade"
    minute: "30"
    hour: "3"
    weekday: "2"