---
- name: "Install root useful packages"
  apt:
    name:
      - vim
      - exuberant-ctags
    state: present

- name: Copy vimrc file configuration to root home
  copy: dest=/root/.vimrc src=root/vimrc owner=root group=root mode=0644

- name: Copy vim specific configuration files to root home
  copy: dest=/root/.vim src=root/vim/ owner=root group=root mode=0644

- name: Copy bash specific configuration files to root home
  copy: dest=/root/.bashrc src=root/bashrc owner=root group=root mode=0644
