---
- name: "Install vincent useful packages : zsh, vim, irssi, screen."
  apt: pkg={{ item }} state=present 
  with_items:
    - zsh
    - screen
    - vim
    - irssi

- name: Create vincent user
  user: name=vincent shell=/bin/zsh groups={{ sudoers_group }}

- name: Copy vimrc file configuration to vincent home
  copy: dest=/home/vincent/.vimrc src=vincent/vimrc owner=vincent group=vincent mode=0644

- name: Copy vim specific configuration files to vincent home
  copy: dest=/home/vincent/.vim src=vincent/vim/ owner=vincent group=vincent mode=0644

- name: Copy zshrc file configuration to vincent home
  copy: dest=/home/vincent/.zshrc src=vincent/zshrc owner=vincent group=vincent mode=0644

- name: Copy zsh specific configuration files to vincent home
  copy: dest=/home/vincent/.zsh src=vincent/zsh/ owner=vincent group=vincent mode=0644

- name: Copy irssi theme files to vincent home
  copy: dest=/home/vincent/.irssi src=vincent/irssi/ owner=vincent group=vincent mode=0644

- name: Copy irssi configuration file to vincent home
  template: dest=/home/vincent/.irssi/config src=vincent/irssi_config owner=vincent group=vincent mode=0644

- name: Copy screenrc file configuration to vincent home
  copy: dest=/home/vincent/.screenrc src=vincent/screenrc owner=vincent group=vincent mode=0644

- name: Set authorized keys for vincent
  authorized_key: user=vincent
                   key="{{ item }}"
  with_file:
  - vincent/public_keys/blue
  - vincent/public_keys/heilong
