---
- name: Setup jenkins certificates 
  command: openssl req -new -nodes -x509 -subj "/C=FR/ST=Paris/L=Paris/O=IT/CN={{ jenkins_hostname }}" -days {{certificate_validity_period_in_days}} -keyout /etc/nginx/ssl/jenkins_server.key -out /etc/nginx/ssl/jenkins_server.crt -extensions v3_ca creates=/etc/nginx/ssl/jenkins_server.crt
  notify: Reload nginx

- name: Create jenkins virtual host
  template: src=virtual_host_config dest=/etc/nginx/sites-available/jenkins
  notify: Reload nginx

- name: Create jenkins link in site-enabled
  file: src=/etc/nginx/sites-available/jenkins state=link dest=/etc/nginx/sites-enabled/jenkins
  notify: Reload nginx 

- name: Create line for jenkins in /etc/hosts
  lineinfile: dest=/etc/hosts line="127.0.0.1 {{ jenkins_hostname }}" insertafter="^127"
