---
- name: Upgrade to latest packages
  become: yes
  become_method: su
  apt: upgrade=full

- name: Install base packages
  apt: name={{ item }} state=present
  become: yes
  become_method: su
  with_items:
    - curl
    - htop
    - rsync
    - tar
    - git
    - sudo
    - python-setuptools

- name: Remove unused packages
  apt: name={{ item }} state=absent purge=yes
  become: yes
  become_method: su
  with_items:
    - exim4
    - exim4-daemon-light
    - exim4-daemon-heavy
    - apache2-bin
    - apache2-data

- name: Install pip
  easy_install: name=pip
  become: yes
  become_method: su
