---
- name: Ensure sudo is present
  apt: name=sudo state=present

- name: Ensure sudoers group is present
  group: name={{ sudoers_group }}

- name: Setup sudoers configuration
  template: src=sudoers dest=/etc/sudoers owner=root group=root mode={{ sudoers_file_permission }} 
  notify: Restart sudo
