---
- name: Create owncloud directory
  file: path={{ owncloud_root_directory }} state=directory recurse=yes owner=root group=www-data mode={{ owncloud_directory_permission }}

- name: Download owncloud
  get_url: url=https://download.owncloud.org/community/owncloud-{{ owncloud_version }}.tar.bz2 dest=/home/commons/downloads/owncloud-{{ owncloud_version }}.tar.bz2
 
- name: Extract owncloud
  unarchive: src=/home/commons/downloads/owncloud-{{ owncloud_version }}.tar.bz2 dest={{ websites_directory }} owner=www-data group=www-data copy=no

- name: Setup owncloud directories owner
  file: path={{ item }} state=directory recurse=yes owner=www-data group=www-data mode={{ owncloud_directory_permission }}
  with_items:
    - "{{ owncloud_root_directory }}/apps"
    - "{{ owncloud_root_directory }}/config"
    - "{{ owncloud_root_directory }}/data"
    - "{{ owncloud_root_directory }}/themes"

- name: Change owner on owncloud htaccess files
  file: path={{ item }} state=file owner=root group=www-data mode={{ owncloud_file_permission }}
  become: yes
  become_method: su
  with_items:
    - "{{ owncloud_root_directory }}/.htaccess"
