---
- name: Setup owncloud certificates
  command: openssl req -new -nodes -x509 -subj "/C=FR/ST=Paris/L=Paris/O=IT/CN={{ owncloud_hostname }}" -days {{certificate_validity_period_in_days}} -keyout /etc/nginx/ssl/owncloud_server.key -out /etc/nginx/ssl/owncloud_server.crt -extensions v3_ca creates=/etc/nginx/ssl/owncloud_server.crt
  notify: Reload nginx

- name: Create owncloud virtual host
  template: src=virtual_host_config dest=/etc/nginx/sites-available/owncloud
  notify: Reload nginx

- name: Create owncloud link in site-enabled
  file: src=/etc/nginx/sites-available/owncloud state=link dest=/etc/nginx/sites-enabled/owncloud
  notify: Reload nginx 

- name: Create line for owncloud in /etc/hosts
  lineinfile: dest=/etc/hosts line="127.0.0.1 {{ owncloud_hostname }}" insertafter="^127"
